name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake g++ libgtest-dev

    - name: Build Google Test
      run: |
        cd /usr/src/googletest
        mkdir -p build
        cd build
        cmake ..
        make
        sudo cp googletest/lib/libgtest.a /usr/lib/
        sudo cp googletest/lib/libgtest_main.a /usr/lib/

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: cmake --build .

    - name: Run tests
      run: ./calculator_test